# Generated by Django 4.0.4 on 2024-03-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_paint_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('bullet_points', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='Base_paint_product_images')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='Blogs_images')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='carousel_background')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STD_NAME', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('COLOR_CODE', models.CharField(max_length=10)),
                ('R', models.IntegerField()),
                ('G', models.IntegerField()),
                ('B', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mbl_no', models.IntegerField()),
                ('pincode', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.TextField(blank=True, max_length=500)),
                ('other_query', models.CharField(blank=True, max_length=50)),
                ('paint_choice', models.CharField(blank=True, max_length=50)),
                ('service_choice', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Exterior_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('bullet_points', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='Exterior_product_images')),
            ],
        ),
        migrations.CreateModel(
            name='Interior_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='Interior_product_images')),
            ],
        ),
    ]
